// This script generates the sidebar items for each SDK based on the activeSDKs array.

// List of SDKs to display on the docs
export const activeSDKs = [
  'Python',
  // 'Dart',
  // 'Kotlin'
];

// Template for the sidebar items for each SDK
// TODO: This type could be improved
const baseSidebarItems: {
  type: 'doc' | 'ref' | 'category',
  id?: string,
  label: string,
  items?: any[],
}[] | {
  type: 'autogenerated',
  dirName: string,
} = [
  {
    type: 'ref',
    id: 'build/index',
    label: '← Back to SDKs',
  },
  {
    type: 'doc',
    id: 'guides/getting-started',
    label: 'Getting Started',
  },
  {
    type: 'category',
    label: 'APIs',
    items: [
      // { type: 'autogenerated', dirName: 'docs_copy/apis' },
      // { type: 'doc', id: 'docs_copy/apis/ActivitiesApi', label: 'Activities API' },
      { type: 'doc', id: 'docs_copy/apis/ApplicationsApi', label: 'Applications API' },
      { type: 'doc', id: 'docs_copy/apis/AssetsApi', label: 'Assets API' },
      { type: 'doc', id: 'docs_copy/apis/ConnectorApi', label: 'Connector API' },
      { type: 'doc', id: 'docs_copy/apis/ConversationsApi', label: 'Conversations API' },
      // { type: 'doc', id: 'docs_copy/apis/ModelsApi', label: 'Models API' },
      // { type: 'doc', id: 'docs_copy/apis/OSApi', label: 'OS API' },
      // { type: 'doc', id: 'docs_copy/apis/SearchApi', label: 'Search API' },
      { type: 'doc', id: 'docs_copy/apis/WellKnownApi', label: 'WellKnown API' },
    ]
  },
  {
    type: 'category',
    label: 'Models',
    items: [
      // { type: 'autogenerated', dirName: 'docs_copy/models' },
      // { type: 'doc', id: 'docs_copy/models/Activity', label: 'Activity' },
      { type: 'doc', id: 'docs_copy/models/Application', label: 'Application' },
      { type: 'doc', id: 'docs_copy/models/Asset', label: 'Asset' },
      { type: 'doc', id: 'docs_copy/models/Assets', label: 'Assets' },
      { type: 'doc', id: 'docs_copy/models/Conversation', label: 'Conversation' },
      // { type: 'doc', id: 'docs_copy/models/Model', label: 'Model' },
      // // { type: 'doc', id: 'docs_copy/models/SearchedAssets', label: 'Searched Assets' },
    ]
  }
];

// Generate sidebar items for each active SDK
export const generatedSDKSidebars = activeSDKs.reduce((acc, sdkName) => {
  const sdkNameLowerCase = sdkName.toLowerCase();

  const itemsWithPrefixedId = baseSidebarItems.map(item => {
    if (item.type === 'ref') {
      return {
        ...item,
      };
    }

    // For top-level doc items, simply prefix the id
    if (item.type === 'doc') {
      return {
        ...item,
        id: `build/sdks/${sdkNameLowerCase}/${item.id}`,
      };
    }

    // For categories, map over the items and prefix their ids
    if (item.type === 'category' && item.items) {

      if (item.items[0].type === 'autogenerated') {
        return {
          ...item,
          items: item.items.map(subItem => ({
            ...subItem,
            dirName: `build/sdks/${sdkNameLowerCase}/${subItem.dirName}`,
          })),
        };
      } else {
        return {
          ...item,
          items: item.items.map(subItem => ({
            ...subItem,
            id: `build/sdks/${sdkNameLowerCase}/${subItem.id}`,
          })),
        };
      }
    }
  });

  acc[`${sdkNameLowerCase}SDKSidebar`] = itemsWithPrefixedId;
  return acc;
}, {});
