name: Bug Report
description: File a bug report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: software
    attributes:
      label: Software
      description: What software are you referring to?
      multiple: true
      options:
        - Desktop Application
        - Pieces OS
        - Web Extension
        - VS Code
        - JetBrains
        - Obsidian
        - Visual Studio
        - Raycast
        - JupyterLab
        - Pieces CLI
        - Microsoft Teams
        - Sharing Web App
        - Sublime Text
        - Azure Data Studio
        - Marketing Site (pieces.app)
        - Blog (code.pieces.app/blog)
        - Release Notes (code.pieces.app/updates)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System / Platform
      description: What operating system / platform are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Web
      default: 0
    validations:
      required: true
  - type: input
    id: pieces-os-version
    attributes:
      label: Your Pieces OS Version
      description: Add the version of Pieces OS installed in your system
    validations:
      required: true
  - type: checkboxes
    id: early_access_program
    attributes:
      label: Early Access Program
      description: Is this issue related to a feature in our Early Access Program?
      options:
        - label: Yes, this is related to an Early Access Program feature.
  - type: textarea
    id: description
    attributes:
      label: Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true