blank_issues_enabled: true
contact_links:
  - name: Feature or Enhancement Request
    url: https://github.com/pieces-app/support/discussions
    about: Post your idea in discussions for the Pieces team and community to discuss!