blank_issues_enabled: false
contact_links:
  - name: Feature, Bug Report, or Enhancement
    url: https://github.com/pieces-app/support/discussions
    about: Post your idea in discussions for the Pieces team and community to discuss!